version: '3'

services:
  ranking1:
    build:
      context: ./ranking
    container_name: movie_rec_ranking_1
    volumes:
      - ./ranking:/go
    ports:
      - 8000:80
    expose:
      - 80
    stdin_open: true
    tty: true
  ranking2:
    build:
        context: ./ranking
    container_name: movie_rec_ranking_2
    volumes:
      - ./ranking:/go
    ports:
      - 8001:80
    expose:
      - 80
    stdin_open: true
    tty: true
  search:
    image: elasticsearch:7.9.3
    container_name: movie_rec_search
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./search/data:/usr/share/elasticsearch/data
  lb:
    image: nginx:1.25.4
    container_name: movie_load_balancer
    ports:
      - 8080:80
    stdin_open: true
    tty: true
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - HOST_IP=192.168.0.2
      - RANKING_1_PORT=8000
      - RANKING_2_PORT=8001
