version: '3'

services:
  ranking:
    build:
      context: ./ranking
    container_name: movie_rec_ranking
    volumes:
      - ./ranking:/go
    ports:
      - 8000:80
    expose:
      - 80
    stdin_open: true
    tty: true
    command: go run main.go 
  search:
    image: elasticsearch:7.9.3
    container_name: movie_rec_search
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./search/data:/usr/share/elasticsearch/data
  lb:
    image: nginx:1.25.4
    container_name: movie_load_balancer
    ports:
      - 8080:80
    stdin_open: true
    tty: true
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf
