version: '3'

services:
  ranking:
    image: goenv:0.0.12
    container_name: movie_rec_ranking
    volumes:
      - .:/go
    ports:
      - 8003:80
    expose:
      - 80
    stdin_open: true
    tty: true
     