version: '3'

services:
  ranking:
    build:
      context: ./ranking
    container_name: movie_rec_ranking
    volumes:
      - ./ranking:/go
    ports:
      - 8003:80
    expose:
      - 80
    stdin_open: true
    tty: true
  search:
    image: elasticsearch:7.9.3
    container_name: move_rec_search
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - ./search/data:/usr/share/elasticsearch/data
